name: CI/CD Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/ISSUE-134
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
        env:
          DEPLOY_SERVER: ${{ secrets.SERVER_HOST }}

      - name: Run deploy script
        env:
          DATABASE_PW: ${{ secrets.DATABASE_PW }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          KAKAO_REDIRECTION_URI: ${{ secrets.KAKAO_REDIRECTION_URI }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          IMAGE_FILE_PATH: ${{ secrets.IMAGE_FILE_PATH }}
          DEPLOY_SERVER: ${{ secrets.SERVER_HOST }}
          DEPLOY_USER: ${{ secrets.SERVER_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: bash remote-deploy.sh
